##**Programação e Algoritmos II**
Prof. Alexandre Levada

##**Complexidade de Algoritmos**

No estudo de programação de computadores, uma característica fundamental dos algoritmos que vamos implementar em uma linguagem de programação é o seu custo computacional. 

Na verdade, durante a análise de complexidade de um programa, estamos interessados em duas propriedades básicas:

1.   Quantidade de memória utilizada
2.   *Tempo de execução*

Problema P e dois algoritmos A1 e A2 que resolvem P, qual é melhor?

Certamente, é aquele que executa mais rápido!

Porém, mais rápido é relativo: computador novo x computador antigo

É preciso um critério objetivo (matemático): *número de instruções a serem executadas*.

Vejamos o exemplo a seguir.


In [ ]:
import time

# Função que soma os n primeiros inteiros
def sum_of_n(n):
	start = time.time()
	sum = 0
	for i in range(1, n+1):
		sum = sum + i
	end = time.time()
 
	return (sum, end-start)
 
# Testa para diferentes valores de entrada
print(sum_of_n(10000))
print(sum_of_n(100000))
print(sum_of_n(1000000))
print(sum_of_n(10000000))
print(sum_of_n(100000000))


(50005000, 0.0010793209075927734)
(5000050000, 0.00952768325805664)
(500000500000, 0.07158803939819336)
(50000005000000, 0.7068150043487549)
(5000000050000000, 6.851905345916748)
(500000000500000000, 67.44953322410583)


Note que quanto maior a entrada (valor de n) mais demorado é a execução do script, pois o número de instruções (iterações do laço FOR) aumenta.

Matematicamente, devemos construir uma função T(n), que conta o número de instruções a ser executada pelo algoritmo. Note que essa função deve ser estritamente crescente, pois se o tamanho da entrada cresce, o número de instruções não pode diminuir.

**A Notação Big-O**

Como não estamos interessados no caso de n pequenos, a ideia é estudar o crescimento assintótico das funções T(n). Para isso, utilizamos a notação Big-O.

Vejamos o caso da função anterior: ao entrar na função temos 3 atribuições. Depois disso, o loop é executado n vezes. Ou seja, T(n) = n + 3

Quando n cresce, apenas uma parte dominante da função é importante (n). O termo 3 é totalmente desprezível.

Vejamos um exemplo mais elaborado.

In [ ]:
import numpy as np

def soma_elementos(A):
  # Calcula a soma dos elementos de uma matriz n x n
  soma_total = 0
  for i in range(n):
	  soma_linha = 0	
	  for j in range(n):
		  soma_linha = soma_linha + A[i,j]
	  soma_total = soma_total + soma_linha

  return soma_total

# Início do script
n = int(input('Entre com o valor de n: '))
matriz = np.random.random((n, n))
print(matriz)
print(soma_elementos(matriz))

Entre com o valor de n: 5
[[0.68680773 0.74344303 0.45645576 0.99213934 0.4257667 ]
 [0.29395765 0.11472441 0.56738131 0.1195973  0.07080301]
 [0.06874301 0.68132629 0.86373137 0.34991135 0.37970959]
 [0.57547276 0.96624038 0.4143063  0.35250742 0.82714442]
 [0.63730381 0.92685539 0.09904289 0.13867772 0.63849281]]
12.390541753850432


Note que no loop mais interno (j) temos n atribuições. Assim para cada valor de i no loop mais externo, temos n + 2 operações. Como temos n possíveis valores para i, chegamos em:

$$
\Large
T(n) = n (n+2) + 1 = n^2 + 2n + 1
$$

Seja f(n) uma função definida para todos os inteiros maiores ou iguais a zero, tal que para uma constante c e uma constante m:

$$
\Large
T(n) \leq c f(n)
$$

para todos os valores suficientemente grandes $n \geq m$ (quando n é grande). Então dizemos que o algoritmo possui complexidade $O(f(n))$. Dessa forma, para o exemplo anterior, considere $c = 2$ e $f(n) = n^2$. Então:

$$
\Large
n^2 + 2n + 1 \leq 2 n^2
$$

para todo $n > 2$, o que implica dizer que o algoritmo em questão é $O(n^2)$.

A função $f(n) = n^2$ não é a única que satisfaz a desigualdade. Por exemplo, a função $g(n) = n^3$, também satisfaz. Porém, para a notação Big-O, nos interessa o limite superior mais apertado possível.

![picture](https://drive.google.com/uc?id=1Yoppi2bKsnU_ETC-przBgB6aMjKIbhV1)


As vezes, o desempenho de um algoritmo não depende apenas do tamanho da entrada, mas também dos elementos que compõem o vetor, o que nos leva a análise de três situações distintas:

1. melhor caso (seria o vetor já ordenado), 
2. caso médio (valores aleatórios)
3. pior caso (o vetor em ordem decrescente, totalmente desordenado).

Em geral, realizamos as análises no caso médio ou pior caso. Costuma-se dividir os algoritmos nas seguintes classes de complexidade:

O(1) - Constante

O(log n) - Logarítmica

O(n) - Linear

O(n log n) - Log-linear

O($n^2$) - Quadrática

O($n^3$) - Cúbica

O($2^n$) - Exponencial

O($n!$) - Fatorial


![picture](https://drive.google.com/uc?id=1sMuTiWflJpFthha8q1qDMrWRPixon9Vr)


A base dos algoritmos que iremos analisar são estruturas de repetição. Porém, estruturas de repetição são representados matematicamente por somatórios. Sendo assim, para construirmos as funções T(n), precisaremos resolver somatórios.

Resolução matemática de somatórios no vídeo:

https://www.youtube.com/watch?v=EDV-ENiaCEA&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=3



**Analisando algoritmos em Python**

A ideia básica é que cada comando de atribuição conta como 1 operação a ser executada, a menos quando ela está associada a uma chamada de função. Nesse caso, devemos contar como m operações, se a complexidade da função for O(m). 

Considere o exemplo a seguir.

In [ ]:
def ex2(n):
     count = 0
     for i in range(n):
          count += 1
     for j in range(n):
          count += 1
     return count

Note que temos uma atribuição inicial (1) e logo dois loops com n iterações. Cada um deles, contribui com n para o total, de modo que no total temos T(n) = 2n + 1, o que resulta em uma complexidade O(n).

Considere o algoritmo a seguir.

In [ ]:
def ex3(n):
     count = 0
     for i in range(n):
          for j in range(n):
               count += 1
     return count

Nesse caso, o loop interno tem n operações. Como o loop externo  é executado n vezes, e temos uma inicialização, o total de operações é $T(n) = n^2 + 1$, o que resulta em complexidade O($n^2$). 

Nem todos os loops aninhados possuem complexidade quadrática.Considere o algoritmo a seguir.



In [ ]:
def ex4(n):
     count = 0
     for i in range(n):
          for j in range(10):
               count += 1
     return count

O loop mais interno é executado 10 vezes (número constante de vezes). Sendo assim, o total de operações é T(n) = 10n + 1, o que resulta em O(n).

Em alguns casos, um dos loops aninhados (em geral o mais interno) executa um número variável de vezes. Considere o algoritmo a seguir.

In [ ]:
def ex5(n):
     count = 0
     for i in range(n) :
          for j in range(i+1) :
               count += 1
     return count 

Note que quando i = 0, o loop interno executa uma vez, quando n = 1, o loop interno executa duas vezes, quando n = 2, o loop interno executa 3 vezes, e assim sucessivamente. Assim, o número de vezes que a variável count é incrementada é igual a: 1 + 2 + 3 + 4 + … + n

Resolução no vídeo:

https://www.youtube.com/watch?v=8KcuGdNgMdc&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=4


Vejamos um outro exemplo ilustrativo.



In [ ]:
def ex6(n):
     count = 0
     i = n
     while i > 1:
          count += 1
          i = i // 2		# divisão inteira
     return count

Essa função calcula quantas vezes o número pode ser dividido por 2. Por exemplo, considere a entrada n = 16. Em cada iteração esse valor será dividido por 2, até que atinja o zero.

16 → 8 → 4 → 2 → 1

A variável count termina a função valendo 4, pois 24 = 16.

Se n = 25, temos:

25 → 12 → 6 → 3 → 1

A variável count  termina a função valendo 4, pois   24 < 25 < 25

Se n = 40, temos:

40 → 20 → 10 → 5 → 2 → 1

A variável count  termina a função valendo 5, pois   25 < 40 < 26

Portanto, o número de iterações do loop é log2 n. Dentro do loop existem duas instruções, portanto neste caso teremos:

$$
\Large
T(n) = 1 + 2\lfloor log_2~n \rfloor
$$

Portanto, a complexidade dessa função é O($log~n$).

Resolução no vídeo:

https://www.youtube.com/watch?v=zezYzmmswyY&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=5


Considere o seguinte exemplo ilustrativo.

In [ ]:
def ex7(n):
     count = 0
     for i in range(n):
          count += ex6(n)
     return count

Note que, como a função ex6(n) tem complexidade logarítmica, e o loop tem n iterações, temos que a complexidade da função em questão é O($n~log~n$).

Veremos a seguir duas funções que realizam a mesma operação: encontrar o menor elemento de uma lista. Qual delas é a mais eficiente? Porque? Justifique sua resposta com argumentos matemáticos.

Resolução no vídeo: 

https://www.youtube.com/watch?v=CQnC_7h3H7Y&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=6

In [ ]:
def menor_A(L):						
  n = len(L)						
  for i in range(n):		
    x = L[i]				
    menor = n*[0]		
    for j in range(n):
      if x <= L[j]:
        menor[j] = 1			            
    if sum(menor) == n:			     
      return (i, x)

def menor_B(L):
  pos = 0
  n = len(L)
  menor = L[pos]
  for i in range(n):     
    if L[i] < menor:     
       pos = i
       menor = L[i]
  return (pos, menor)	      

L = [5, 3, 9, 7, 2, 1, 8, 6, 4]    
print(menor_A(L))
print(menor_B(L))

(5, 1)
(5, 1)


**O Problema da Torre de Hanói**

Imagine que temos 3 hastes (A, B e C) e inicialmente n discos de tamanhos distintos empilhados na haste A, de modo que discos maiores não podem ser colocados acima de discos menores.

![picture](https://drive.google.com/uc?id=1QOEXPW5iDV4J3ULuzEUbyZbtmiNsL_x9)

O objetivo consiste em mover todos os discos para uma outra haste. Há apenas duas regras: 

1. Podemos mover apenas um disco por vez
2. Não pode haver um disco menor embaixo de um disco maior

Vejamos o que ocorre para diferentes valores de n (número de discos).

Se n = 1, basta 1 movimento: 
    *Move A, B*

Se n = 2, são necessários 3 movimentos: 	
    
*Move A, B*

*Move A, C*
		
*Move B, C*

Se n = 3, são necessários 7 movimentos:

*Move A, B*

*Move A, C*

*Move B, C*

*Move A, B*

*Move C, A*

*Move C, B*

*Move A, B*

Utilizando uma abordagem recursiva, note que se n = 4, são necessários 15 movimentos: temos 7 movimentos para os 3 menores discos, 1 movimento para o maior e mais 7 movimentos para os 3 menores, o que totaliza 7 + 1 + 7 = 15 movimentos

Se n= 5, teremos 15 + 1 + 15 = 31 movimentos.


---


Em resumo, temos o seguinte algoritmo recursivo

1. Para mover n – 1 discos menores: $T_{n-1}$ movimentos

2. Para mover o maior disco: 1 movimento

3. Para mover de volta os n – 1 discos menores: $T_{n-1}$ movimentos

Assim, a recorrência fica definida como:

$$
\Large
T_1 = 1 \\
\Large
T_{n} = 2 T_{n-1} + 1
$$

Pergunta: Como calcular uma função T(n) dada a recorrência?

Resolução matemática no vídeo:

https://www.youtube.com/watch?v=AKowhHrXj20&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=7 

---

**Busca sequencial**

Uma tarefa fundamental na computação consiste em dado uma lista e um valor qualquer, verificar se aquele valor pertence a lista ou não. Essa funcionalidade é usada por exemplo em qualquer sistema que exige o login de um usuário (para verificar se o CPF da pessoa está cadastrada). Faça uma função que, dada uma lista de inteiros L e um número inteiro x, verifique se x está ou não em L. A função deve retornar o índice do elemento (posição) caso ele pertença a ele ou o valor lógico False se ele não pertence a L. (isso equivale ao operador in de Python). O código em Python a seguir implementa a busca sequencial.

In [ ]:
def busca_sequencial(L, x): 
	achou = False 
	i = 0 
	while i < len(L) and not achou: 
		if (L[i] == x): 
			achou = True 
			pos = i	 
		else: 
			i = i + 1		
 
	if achou: 
		return pos 
	else: 
		return achou

########################
# Início do script
########################
L = [5, 3, 7, 9, 1, 8, 2, 4]
print(busca_sequencial(L, 1))
print(busca_sequencial(L, 99))


4
False


Vamos analisar a complexidade da busca sequencial no pior caso, onde o elemento a ser buscado x está na última posição da lista ou não faz parte do conjunto.

Note que o loop entra n-1 vezes no else e exatamente 1 vez no if, o que nos leva a:

$$
\Large
T(n) = 2 + (n-1) + 2 = n + 3
$$

o que resulta em complexidade O(n).

---

**Busca Binária**

A busca binária requer uma lista ordenada de elementos para funcionar. Ela imita o processo que nós utilizamos para procurar uma palavra no dicionário. Como as palavras estão ordenadas, a ideia é abrir o dicionário mais ou menos no meio. Se a palavra que desejamos inicia com uma letra que vem antes, então nós já descartamos toda a metade final do dicionário (não precisamos procurar lá, pois é certeza que a palavra estará na primeira metade. 

No algoritmo, temos uma lista com números ordenados. Basicamente, a ideia consiste em acessar o elemento do meio da lista. Se ele for o que desejamos buscar, a busca se encerra. Caso contrário, se o que desejamos é menor que o elemento do meio, a busca é realizada na metade a esquerda. Senão, a busca é realizada na metade a direita. A seguir mostramos um script em Python que implementa a versão recursiva da busca binária.

In [ ]:
# Função recursiva (ela chama a si própria)
def busca_binaria(L, x, ini, fim):
    meio = (ini + fim) // 2
    if ini > fim:
        return -1   		# elemento não encontrado
    elif L[meio] == x:
        return meio
    elif L[meio] > x:
        print('Buscar na metade inferior')
        return busca_binaria(L, x, ini, meio-1)
    else:
        print('Buscar na metade superior')
        return busca_binaria(L, x, meio+1, fim)

########################
# Início do script
########################
L = [5, 3, 7, 9, 1, 8, 2, 4]
# Ordena lista
L.sort()
# Realiza busca
print(busca_binaria(L, 1, 0, len(L)-1))
print(busca_binaria(L, 99, 0, len(L)-1))

Buscar na metade inferior
Buscar na metade inferior
0
Buscar na metade superior
Buscar na metade superior
Buscar na metade superior
Buscar na metade superior
-1



Uma comparação enter o pior caso da busca sequencial e da busca binária, mostra a significativa diferença entre os métodos. Na busca sequencial, faremos n acessos para encontrar o valor procurado na última posição. Costuma-se dizer que o custo é O(n) (é da ordem de n, ou seja, linear). Na busca binária, como a cada acesso descartamos metade das amostras restantes. Supondo, por motivos de simplificação, que o tamanho do vetor n é uma potência de 2, ou seja, n = 2m, note que:

m = 1 		→ 	n/2 descartados

m = 2 		→ 	n/4 descartados

m = 3 		→	  n/8 descartados

m = 4 		→ 	n/16 descartados

e assim sucessivamente. É possível notar um padrão? Quantos acessos devemos realizar para que descartemos todo o vetor? Devemos ter n / 2m = 1, o que  significa ter n = 2m , o que implica em m = log2 n, ou seja, temos um custo O(log2 n) o que é bem menor do que n quando n cresce muito, pois a função log(n) tem uma curva de crescimento bem mais lento do que a função linear n. Veja que a derivada (taxa de variação) da função linear n é constante e igual a 1 sempre. A derivada da função log(n) é 1/n, ou seja, quando n cresce, a taxa de variação, que é o que controla o crescimento da função, decresce. Na prática, isso significa que em uma lista com 1024 elementos, a busca sequencial fará no pior caso 1023 acessos até encontrar o elemento desejado. Na busca binária, serão necessários apenas log2 1024 = 10 acessos, o que corresponde a aproximadamente 1% do necessário na busca sequencial! É uma ganho muito grande. Porém, na busca binária precisamos gastar um tempo para ordenar a lista! 

Discussão no vídeo:
https://www.youtube.com/watch?v=41N7iaLsUZQ&list=PL7OlISixQYm6lhuuNEadZ_ua4qCVl6zH7&index=8


Para isso precisaremos de algoritmos de ordenação, o que é o assunto da nossa próxima aula. 

"You are a piece of the puzzle of someone else's life. You may never know where you fit, but others will fill the holes in their lives with pieces of you." (Bonnie Arbon)